name: Deploy React Automatico

on:
  push:
    branches: ["main"] # Mude para master se sua branch principal for master

# Permissões necessárias para o GitHub Actions fazer o deploy no Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar Dependencias
        run: npm ci # Instalação limpa e mais rápida para CI

      - name: Criar Build do React
        run: npm run build

      - name: Enviar Arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          # ATENÇÃO: Se usar Create React App, mude 'dist' para 'build'
          path: './dist' 

  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

